### ISSUE TITLE
AttributeCollector#getNsCount() is protected (should be public)

### ISSUE THREAD

**Issue by DelRed2** [FasterXML/woodstox#115]
https://github.com/FasterXML/woodstox/blob/3696a7370948f5510ddd0728a1f3679fa1297aa8/src/main/java/com/ctc/wstx/sr/AttributeCollector.java#L281

Comment above says: Public accesors (for stream reader)
but is is protected, so I can not use it in my API.

**Comment by cowtowncoder** [comment]
I don't think this class was ever meant to be used by anything outside of Woodstox itself: it is not exposed via public API is it?
(obv. cannot be part of Stax 1.x, but I don't think Stax2 `XMLStreamReader2` or `XMLStreamWriter2` expose it either).

So I am not sure why its accessor ought to be public. Perhaps access to it should be blocked more effectively, however.

**Comment by cowtowncoder** [comment]
Adding a label to indicate that additional justification is needed for why this should be made available -- class is not part of public API and as such not a designed extension point.
