### ISSUE TITLE
NoClassDefFoundError: IgnoreController

### ISSUE THREAD

**Issue by matthjes** [FasterXML/woodstox#126]
Hi,
I'm in the middle of migrating a JDK 8 project to JDK 11. One thing that gives my headaches are the following errors:
```
java.lang.NoClassDefFoundError: com/sun/msv/reader/util/IgnoreController

	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```
Debugging with IntelliJ shows that this class is used in `com.ctc.wstx.msv.BaseSchemaFactory$MyGrammarController`, which seems to be included in
```
<!-- https://mvnrepository.com/artifact/fish.payara.extras/payara-embedded-all -->
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-embedded-all</artifactId>
    <version>5.201</version>
    <scope>test</scope>
</dependency>
```
Any idea what needs to be included as well to get rid of these errors?

EDIT: Before switching to Payara 5 we used Payara 4 (version: 4.1.2.173.0.1), which included the `IgnoreController` class. It seems like this class is no longer present in version 5.

**Comment by pjfanning** [comment]
The project readme file says

```
Optional dependency is Multi-Schema Validator (MSV) that is needed if using XML Schema or RelaxNG validation functionality
```

**Comment by matthjes** [comment]
Hi,
I've looked deeper into this and it turned out that there were some weird things going on with class loading. For context, I'm using CDI-Unit for the tests.

The error occurred when I added a specific class via `@AdditionalClasspaths`. This loaded more project classes then expected, which somehow triggered the loading of some classes inside payara-embedded-all dependency which then lead to this error.

I've solved this by moving the class into CDI-Units `@AdditionalPackages`, which does not seem to trigger the extensive class loading.

**Comment by cowtowncoder** [comment]
Ok I'm glad you were able to figure out a way forward. Problem with MSV which is like @pjfanning mentioned, an optional dependency for schema validation, is that it is an old and (at this point mostly) unmaintained package. This means that it does not have module-info as far as I know -- although if someone takes time, creating a new version with basic info (using Moditect plugin) might not be super hard to do.

I would be open for improvements in Woodstox to try to further isolate loading, if possible, as well.
