### ISSUE TITLE
`com.ctc.wstx.evt` is not exported in `module-info.java`

### ISSUE THREAD

**Issue by ChrisTrenkamp** [FasterXML/woodstox#136]
I'm attempting to migrate an application to JPMS.  It depends on the `com.ctc.wstx.evt` package, but it is not exported in woodstox-core's `module-info.java`, causing compilation errors.

Can `com.ctc.wstx.evt` be exported?

**Comment by cowtowncoder** [comment]
Whops. It does seem to be missing, will add.

Thank you for reporting the issue.

**Comment by cowtowncoder** [comment]
Decided to release 6.2.8 with this fix, will be at Maven Central in due time.
