### ISSUE TITLE
Migrate to Jakarta EE 9 aka jakarta.xml.bind

### ISSUE THREAD

**Issue by thetric** [FasterXML/woodstox#138]
With the [release of Jakarta EE 9 in the end of 2020](https://www.eclipse.org/community/eclipse_newsletter/2020/november/1.php) the package names of many formally Java EE APIs have changed. The JAXB APIs are no exception. The new Maven artifacts are:

> * jakarta.xml.bind:jakarta.xml.bind-api:3.0.0 + com.sun.xml.bind:*:3.0.0

This would also require a baseline of Java 8, see #134

**Comment by cowtowncoder** [comment]
Could you elaborate on this? Woodstox does not implement nor use JAXB.

The only reference I see is via "isorelax" dependency (using namespace).

**Comment by thetric** [comment]
Sorry, my fault. I thought that some apis were coupled to Java EE
