### ISSUE TITLE
OSS-Fuzz Integration of woodstox

### ISSUE THREAD

**Issue by 0roman** [FasterXML/woodstox#141]
Hi all,

I prepared the initial integration (https://github.com/CodeIntelligenceTesting/oss-fuzz/commit/b88800f106f3ee1dd035a072a12832933815abfa) of woodstox into Google oss-fuzz. This will enable continuous fuzzing of this project, which will be conducted by google. The fuzz targets will be enhanced over time. Bugs that will be found by fuzzing will be reported to you. 

Ideal integration requires a primary contact, who will will receive Bug reports found by oss-fuzz. The email address needs to belong to an established project committer. Please let me know who should I include.

[Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) is used for fuzzing Java applications. Jazzer is a coverage-guided, in-process fuzzer for the JVM platform developed by Code Intelligence. It is based on libFuzzer and brings many of its instrumentation-powered mutation features to the JVM. 
Jazzer has already found a lot of critical [bugs](https://github.com/CodeIntelligenceTesting/jazzer#findings) in JVM applications.

Please let me know if you have any questions regarding fuzzing or the oss-fuzz integration.

**Comment by cowtowncoder** [comment]
Hi @0roman! Thank you for adding the integration.

I think my "maintainer" address would be

    tatu@fasterxml.com

and that is already used for Jackson_databind and Jackson_core OSS Fuzzer projects.

**Comment by 0roman** [comment]
Sounds good. Thank you for the fast response.
