### ISSUE TITLE
Typo: "expected" misspelled as "excepted"

### ISSUE THREAD

**Issue by pdo-axelor** [FasterXML/woodstox#147]
https://github.com/FasterXML/woodstox/blob/80e19371ac32f7e90e76d04e6c2fd02dea52d36c/src/main/java/com/ctc/wstx/sr/BasicStreamReader.java#L1948
https://github.com/FasterXML/woodstox/blob/master/src/main/java/com/ctc/wstx/sr/BasicStreamReader.java#L3083
https://github.com/FasterXML/woodstox/blob/master/src/main/java/com/ctc/wstx/sr/BasicStreamReader.java#L3191
https://github.com/FasterXML/woodstox/blob/master/src/main/java/com/ctc/wstx/sr/BasicStreamReader.java#L4030

**Comment by cowtowncoder** [comment]
Sounds like something to fix. PR would be awesome?
