### ISSUE TITLE
How do configure to write '&' instead '&amp;

### ISSUE THREAD

**Issue by JulioCesGO** [FasterXML/woodstox#152]
I use the woodstox to write a xml , when i write the word 'Rela&amp;#231;&amp;#227;o' (with accent is Relação) , in xml is wrote:  Rela&amp;#231;&amp;#227;o. Are there a configuration to resolve my problem?

**Comment by cowtowncoder** [comment]
You don't. XML parsers must escape character `&`, either as `&amp;` or as its numeric equivalent (`&#26;`).
So if you want to write accented characters, you write accented characters and let XML parser write it -- it may choose to write it as-is, or escape.

Having said that, if you really, really want to by-pass all processing, there is method `writeRaw()` in `XMLStreamWriter2` (extension of `XMLStreamWriter` that Woodstox implements):

https://javadoc.io/static/org.codehaus.woodstox/stax2-api/4.2.1/org/codehaus/stax2/XMLStreamWriter2.html#writeRaw-java.lang.String-

which will include String in output exactly as you give it. That does allow you to specify escpaing.
