### ISSUE TITLE
Cannot build RCP application after update to 6.3.0

### ISSUE THREAD

**Issue by selundqma** [FasterXML/woodstox#154]
Hi! Thank you for all your important work! I have been using your plugins for many years and they have been GREAT :). Now I contact you to hopefully get an hint why my Eclipse RCP application (building with Maven and Tycho 2.7.4) build does not succeed after going from 6.2.8 to 6.3.0 of the woodstox-core plugin. That is the ONLY change I did.

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:2.7.4:validate-classpath (default-validate-classpath) on project com.selundqma.cs.ma.client.bordet: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:2.7.4:validate-classpath failed: org.osgi.framework.BundleException: Bundle com.selundqma.cs.ma.client.bordet cannot be resolved:com.selundqma.cs.ma.client.bordet [181]
[ERROR]   Unresolved requirement: Require-Bundle: com.sun.xml.ws.jaxws-rt
[ERROR]     -> Bundle-SymbolicName: com.sun.xml.ws.jaxws-rt; bundle-version="4.0.0"
[ERROR]        com.sun.xml.ws.jaxws-rt [149]
[ERROR]          Unresolved requirement: Import-Package: com.sun.xml.ws.assembler.metro.jaxws; resolution:="optional"
[ERROR]          Unresolved requirement: Import-Package: com.ctc.wstx.stax; version="[6.2.0,7.0.0)"
[ERROR]            -> Export-Package: com.ctc.wstx.stax; bundle-symbolic-name="com.fasterxml.woodstox.woodstox-core"; bundle-version="6.3.0"; version="6.3.0"
[ERROR]               com.fasterxml.woodstox.woodstox-core [106]
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.grammar; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.grammar.trex; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.grammar.xmlschema; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.reader; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.reader.trex.ng; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.reader.util; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.reader.xmlschema; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.util; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.verifier; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.verifier.regexp; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: com.sun.msv.verifier.regexp.xmlschema; version="[2013.6.0,2014.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Import-Package: org.relaxng.datatype; resolution:="optional"
**[ERROR]                 Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.serviceloader.registrar)(version>=1.0.0)(!(version>=2.0.0)))"**
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by cowtowncoder** [comment]
Hmmh. Unfortunately I do not know much about OSGi so I don't immediately know what might be causing this, or how to resolve the issue.

Looking at release notes I suspect that this is related to one or both of:

* #133: Update "org.osgi.core" dependency from one published in 2009 to something newer
* #151: Add standard osgi.serviceloader OSGi metadata for provided services

So maybe looking through those could help.

**Comment by cowtowncoder** [comment]
@chrisr3 I wonder if you might know what is going in here?

**Comment by chrisr3** [comment]
> @chrisr3 I wonder if you might know what is going in here?

OSGi is saying that it would like you to install something to provide the `osgi.serviceloader.registrar` capability. In other words, [Apache Aries SPI-Fly](https://mvnrepository.com/artifact/org.apache.aries.spifly/spifly):
```
org.apache.aries.spifly:org.apache.aries.spifly.dynamic.framework.extension:1.3.5
```

**Comment by selundqma** [comment]
Now we are talking! It works by adding the suggested POM dependency:

`org.apache.aries.spifly:org.apache.aries.spifly.dynamic.framework.extension:1.3.5`

Thank you very much! I hope you can add this dependency to your project so that all people get it automatically. Or, document that it is needed for some OSGI builds :).

**Comment by chrisr3** [comment]
> Thank you very much! I hope you can add this dependency to your project so that all people get it automatically. Or, document that it is needed for some OSGI builds :).

SPI-Fly is only needed by OSGi frameworks, and even then only to make the `META-INF/services/*` files accessible to `ServiceLoader`. So adding it as a dependency to `woodstox-core` may be "overkill" :wink:. I am suggesting making the requirement "optional" instead so that people who want to use `ServiceLoader` still can, but everyone else can continue as usual.

And to be clear: no-one using `woodstox-core:6.3.0` _outside_ of an OSGi framework will have this issue.

**Comment by selundqma** [comment]
Thanks for the clarification! I agree, making the requirement "optional" will help a lot and will do the work! Thanks again for everything :).

**Comment by cowtowncoder** [comment]
Ok, I think that with merging of #155 this may be closed. I hope to get Woodstox 6.3.1 patch out soon which should work around the issue.
