### ISSUE TITLE
XMLEvent.asCharacters() throws a cast error on Kotlin

### ISSUE THREAD

**Issue by Kryomancer** [FasterXML/woodstox#166]
I'm trying to make use of the library on Kotlin, but I cannot call asCharacters() on the events it returns. [A tutorial](https://www.baeldung.com/java-stax) I've followed suggests doing this to get the contents of a tag. [My full code is here](https://gist.github.com/Kryomancer/19936f5ba0338a52faa1dd4364e89e99#file-xmlparser-kt-L36), the call ot `asCharacters` on line 36 is the first part where this fails.

The problematic part is:

`var someString = nextEvent.asCharacters().data`

which throws 

```
Exception in thread "main" java.lang.ClassCastException: com.ctc.wstx.evt.CompactStartElement cannot be cast to javax.xml.stream.events.Characters
	at org.codehaus.stax2.ri.evt.BaseEventImpl.asCharacters(BaseEventImpl.java:47)
```

Calling `isCharacters` on the event returns false, but I'm 100% certain all elements this gets called on do contain a value within them. How do I access this value?

**Comment by Kryomancer** [comment]
My problem was that the tutorial was wrong and doesn't show that you need to get the next event after the starting tag.

**Comment by cowtowncoder** [comment]
@Kryomancer ok thank you for adding update & great things work now.
