### ISSUE TITLE
README links https://www.studytrails.com are problematic

### ISSUE THREAD

**Issue by pjfanning** [FasterXML/woodstox#167]
the links in README to https://www.studytrails.com have invalid certs and browsers make the pages very hard to get to.

* eg https://www.studytrails.com/2016/09/12/java-xml-woodstox-introduction/

It may a good idea to put the docs in the woodtox wiki or something like that.

**Comment by cowtowncoder** [comment]
Oh rat. These are main tutorials here... ok, will need to see if we can find replacements.

**Comment by cowtowncoder** [comment]
Went ahead, removed links; added 2 others (although possibly not as extensive).
