### ISSUE TITLE
Version 6.6.0 contains a module error (dup of #193 ?)

### ISSUE THREAD

**Issue by GedMarc** [FasterXML/woodstox#199]
Module com.ctc.wstx does not read a module that exports com.ctc.wstx.shaded.msv.org_isorelax.verifier

:)

**Comment by cowtowncoder** [comment]
@GedMarc is this same as #193? Which was (... I hope) fixed for just-release 6.6.1.

**Comment by GedMarc** [comment]
It is it is whoop :) <3

Much appreciated thank you!!
