### ISSUE TITLE
Fix shading of `isorelax` dependency (and other msv-core components)

### ISSUE THREAD

**Issue by norrisjeremy** [FasterXML/woodstox#200]
Is it intended that `isorelax` is no longer shaded into the final artifact published to Maven Central?

It appears this started with the `6.6.0` release, because `net.java.dev.msv:msv-core:2022.7` now depends upon `isorelax:isorelax:20030108`, unlike the previous `net.java.dev.msv:msv-core:2013.6.1` that instead depended upon `com.sun.xml.bind.jaxb:isorelax:20090621`.

The `isorelax:isorelax:20030108` artifact no longer matches the artifactSet include declaration in the [POM file here](https://github.com/FasterXML/woodstox/blob/f98fec4f8db860c7ba3c62630c15d3edf1f7355d/pom.xml#L283), therefore it is not processed by the relocation declarations, and thus is not shaded in the final artifact that is published to Maven Central.

**Comment by norrisjeremy** [comment]
Also, I'm not sure if the shading of `isorelax` should just be blindly changed to `isorelax:isorelax:20030108` instead of `com.sun.xml.bind.jaxb:isorelax:20090621`.

I noticed while [browsing Maven Central](https://repo1.maven.org/maven2/isorelax/isorelax/20030108/) that the `isorelax:isorelax:20030108` does not have any published source code artifact, so a better solution to this may be to manually exclude the `isorelax:isorelax:20030108` transitive dependency pulled in by `net.java.dev.msv:msv-core:2022.7` and instead add an explicit dependency upon `com.sun.xml.bind.jaxb:isorelax:20090621`, so that a version of `isorelax` that includes a source code artifact is what ultimately ends up being shaded into Woodstox.

I can submit a PR if that would help?

**Comment by cowtowncoder** [comment]
@norrisjeremy I am 99% sure change is unintentional, and based on misunderstanding that the included Java packages were same between artifacts.
However: it also sounds like `msv-core` release had potential issue: I am not 100% sure if the change was intentional there wrt `isorelax`dependency -- it might (trying to avoid ref to Sun-specific release), or it might not be. I don't know.

Be all of that as it may, yes, a PR to make MSV and its dependencies properly shaded would be very helpful -- probably against `6.6` branch so it could go in `6.6.2` (I think), as well as `master` for upcoming 7.0.0 release.

**Comment by cowtowncoder** [comment]
Btw, sounds like #193 might be related?

**Comment by norrisjeremy** [comment]
@cowtowncoder Do you have any sort of CLA that you would need from me to contribute a PR for this? There are no code related changes, it's simply a few changes to the `pom.xml`.

**Comment by norrisjeremy** [comment]
Yes, this may well be actual cause of #193.
Was a simple reproducer provided for it that could be used to test and confirm if my proposed changes in #202 would resolve it with 5a263999 reverted?

**Comment by cowtowncoder** [comment]
Unfortunately there was no reproducer for #193: one practical problem being that the JDK baseline for building things is JDK 8, and there is no good way (AFAIK) to test module-info before JDK 9 (where JPMS was introduced).
It's not impossible to make work with multi-module build (or separate repo etc), just complicated enough that I don't have time to dig into.
But we did get a developer to try out a build to manually verify work-around.

As to `VerifierFactoryLoader`... I think that as long as all Woodstox unit tests pass, I'd be ok in assuming SPI information was not necessary; these dependencies are strictly for Woodstox private use.

**Comment by cowtowncoder** [comment]
@norrisjeremy One thing I did forget to ask -- why does this matter? As in, what problem is being fixed? I was assuming this is due to something breaking (validation not working); exception being thrown or so? But that would be good to include since inclusion of various components is only to support XML Schema / RelaxNG validation and nothing else.

**Comment by norrisjeremy** [comment]
> @norrisjeremy One thing I did forget to ask -- why does this matter? As in, what problem is being fixed? I was assuming this is due to something breaking (validation not working); exception being thrown or so? But that would be good to include since inclusion of various components is only to support XML Schema / RelaxNG validation and nothing else.

We routinely audit various library dependencies that we utilize for our internally built applications and noticed that the 6.6 Woodstox releases no longer included the shaded copy of `isorelax`.

I also completed an analysis and concluded that not shading `isorelax` could break at least the following three classes:
1. `com.ctc.wstx.msv.RelaxNGSchemaFactory`: uses `com.sun.msv.reader.trex.ng.RELAXNGReader` from `msv-core`, which in turn uses `org.iso_relax.verifier.Schema` from `isorelax`.
2. `com.ctc.wstx.msv.W3CSchemaFactory`: uses `com.sun.msv.reader.xmlschema.XMLSchemaReader` from `msv-core`, which in turn uses `org.iso_relax.verifier.Schema` from `isorelax`.
3. `com.ctc.wstx.msv.W3CMultiSchemaFactory`: uses `com.sun.msv.reader.xmlschema.XMLSchemaReader` from `msv-core`, which in turn uses `org.iso_relax.verifier.Schema` from `isorelax`.

**Comment by cowtowncoder** [comment]
Ok that makes sense. I will add another question on PR itself then.

**Comment by cowtowncoder** [comment]
Merged; I also released Woodstox 6.6.2 with just this one change.

**Comment by norrisjeremy** [comment]
> Merged; I also released Woodstox 6.6.2 with just this one change.

Great, thanks!
