### ISSUE TITLE
SAXParser: Add support for `LexicalHandler.startEntity()` and `.endEntity()`

### ISSUE THREAD

**Issue by philippn** [FasterXML/woodstox#209]
Hi there,

I've been looking at migrating some of our code from Apache Xerces to Woodstox. So far it works great (thanks for the great work!), but there is one issue that I stumbled about.

Consider your have an entity reference somewhere in your XML (please bear with me for the silly example)

```
    <meta>
        <prodname>eyePhone&copyright; 2.0</prodname>
        <company>MomCorp</company>
        <prodtype>mobile phone</prodtype>
        <source>http://theinfosphere.org/EyePhone</source>
    </meta>
```

The referenced entity is correctly supplied in the DTD.

Now when I parse this file with Xerces and let the receiving handler print out the events it receives, I end up with this:

> [main] INFO LoggingXMLFilter - Start element:  meta meta
> [main] INFO LoggingXMLFilter - Start element:  prodname prodname
> [main] INFO LoggingXMLFilter - Characters: eyePhone
> [main] INFO LoggingXMLFilter - Start entity: copyright
> [main] INFO LoggingXMLFilter - Characters: ©
> [main] INFO LoggingXMLFilter - End entity: copyright
> [main] INFO LoggingXMLFilter - Characters:  2.0
> [main] INFO LoggingXMLFilter - End element:  prodname prodname

In contrast, Woodstox by default produces this: 

> [main] INFO LoggingXMLFilter - Start element:  meta meta
> [main] INFO LoggingXMLFilter - Start element:  prodname prodname
> [main] INFO LoggingXMLFilter - Characters: eyePhone© 2.0
> [main] INFO LoggingXMLFilter - End element:  prodname prodname

I have already figured out that when I call `doReplaceEntityRefs(false);` on the factory, the result changes to

> [main] INFO LoggingXMLFilter - Start element:  meta meta
> [main] INFO LoggingXMLFilter - Start element:  prodname prodname
> [main] INFO LoggingXMLFilter - Characters: eyePhone
> [main] INFO LoggingXMLFilter - Skipped entity: copyright
> [main] INFO LoggingXMLFilter - Characters:  2.0
> [main] INFO LoggingXMLFilter - End element:  prodname prodname

But given that I have supplied a `LexicalHandler` I would actually expect the same call sequence as with Xerces.

I have looked into this further and my solution for it would be something along those lines: https://github.com/FasterXML/woodstox/compare/master...philippn:woodstox:feature/start-end-entity

If you find this sensible, I would be happy to provide a pull request. I can also provide the silly sample code, just let me know and I can upload it as well :-)

Thanks in advance and kind regards,
Philipp

**Comment by cowtowncoder** [comment]
@philippn It's been a while since I worked in this area, but what you describe makes sense. So I would be happy to help with a PR, especially with some test coverage for the new behavior.

**Comment by cowtowncoder** [comment]
Also: thank you for the kind words. I am happy SAX implementation gets some usage too... and works to a degree (being newer part of codebase and having gotten less usage in general).

**Comment by philippn** [comment]
I have opened a PR now and it also includes a basic test case covering the functionality. Please note my comment regarding the switch on the STAX factory. It would be great if there was a way to enable this more elegantly (without having to go through the STAX factory).

**Comment by philippn** [comment]
Thanks for merging the PR! 

Since you are open to change the default behaviour for the SAX side, I would probably prefer that option too. Because that would align woodstox with the behaviour of other SAX Parsers, namely Xerces and JDKs built in parser, which is basically just a fork of an older Xerces.

I will work on a new PR next week. Thanks agai!
