### ISSUE TITLE
SAX: `Locator#getSystemId` and `Locator#getPublicId` are not available during `startDocument` event

### ISSUE THREAD

**Issue by philippn** [FasterXML/woodstox#213]
Hi there,

I have been looking at the SAX parsing again and noticed that there is another tiny problem. Basically it occurs, when you try to access the `Locator` properties during the `startDocument` event. Here the `systemId` can be useful in particular, but since the `mScanner` is not initialized yet, `null` is returned instead.

A simple solution is to defer the `startDocument` and `setLocator` calls until after the `mScanner` is initialized. 

I have implemented this in a branch (https://github.com/philippn/woodstox/tree/bugfix/fix-locator-for-saxon), tested it and could provide a PR if you are interested (although it's really quite trivial).

Thanks in advance and kind regards,
Philipp

**Comment by cowtowncoder** [comment]
On Mon, Nov 11, 2024 at 6:59 AM Philipp Nanz ***@***.***>
wrote:

> Hi there,
>
> I have been looking at the SAX parsing again and noticed that there is
> another tiny problem. Basically it occurs, when you try to access the
> Locator properties during the startDocument event. Here the systemId can
> be useful in particular, but since the mScanner is not initialized yet,
> null is returned instead.
>
> A simple solution is to defer the startDocument and setLocator calls
> until after the mScanner is initialized.
>
> I have this implemented in a branch (
> https://github.com/philippn/woodstox/tree/bugfix/fix-locator-for-saxon)
> and could provide a PR if you are interested (although it's really quite
> trivial).
>
> Thanks in advance and kind regards,
> Philipp
>

Thank you for reporting this, and especially for the offer to do a PR --
I'd happily accept one as that typically speeds up things when I don't have
to do as much context switching (I trust it is indeed straight-forward but
I juggle a couple of OSS projects so context is often lost).

-+ Tatu +-

**Comment by cowtowncoder** [comment]
Excellent. Now merged, to be included in (eventual) 7.1.1
