### ISSUE TITLE
Cleanup: unused private static arrays in `WstxInputData` and `StreamScanner`

### ISSUE THREAD

**Issue by winfriedgerlach** [FasterXML/woodstox#216]
- `WstxInputData` features two private byte arrays `sCharValidity` and `sPubidValidity` that are not used anywhere. I assume these are historic leftovers that moved to `StreamScanner`(git history doesn't reach that far back) and can be safely removed together with their static initializer blocks? If so, you can also remove the fields `VALID_CHAR_COUNT`, `NAME_CHAR_INVALID_B`, `NAME_CHAR_ALL_VALID_B`, `NAME_CHAR_VALID_NONFIRST_B`, `VALID_PUBID_CHAR_COUNT`, `PUBID_CHAR_VALID_B` (probably all of the block "Character validity constants, structs")
- `StreamScanner` has the same two static arrays `sCharValidity` and `sPubidValidity`, but only `sPubidValidity` is used. Can the other one be removed?

**Comment by cowtowncoder** [comment]
Yes, I think those sound reasonable, pr would be welcome.

**Comment by winfriedgerlach** [comment]
@cowtowncoder here you are #217

**Comment by winfriedgerlach** [comment]
@cowtowncoder as you can see, I have prepared another cleanup PR to use some more modern Java constructs in old test code
I also have some suggestions for productivity code, but let's do it step by step

**Comment by winfriedgerlach** [comment]
@cowtowncoder thanks for merging the original issue, maybe you are also interested in cleaning up and using more modern Java features in test code --> #219
