### ISSUE TITLE
Woodstox conflict with BeanIO parser, when reading XML file with CDATA

### ISSUE THREAD

**Issue by hussein-ahmed** [FasterXML/woodstox#27]
hallo, 

Parsing a XML-File with beanio.org framework and Woodstox as default implementation works fine as long as the CDATA-Text doesn't exist.

Problem is: it ignores CDATA-Tag as if it doesn't exist, so we can't read as long as woodstox is in classpath.

beanio does read it fine with "com.sun.xml.internal.stream.XMLInputFactoryImpl"... as soon as we add woodstox jar to classpath it takes woodstox as default implementation.

we use "woodstox-core-asl-4.2.0.jar"

can you please follow this issue and tell me if you have any clue on what could the prblem be.

best regards.

thanks

**Comment by cowtowncoder** [comment]
@hussein-ahmed Woodstox does not ignore CDATA, but depending on settings may expose it as CHARACTERS, as per Stax specification. Difference between CDATA and regular text segments is not logically meaningfully in XML processing (it's just a convenience feature mostly for manual editing).

So I think I would need a test case to show what the issue you are seeing is; I may be misunderstanding what you are saying.

One small thing you may want to do, as well, is to upgrade woodstox 4.x dependency to latest release (4.4.1) -- API and behavior should be identical, but there are some bug fixes that may be relevant.

**Comment by cowtowncoder** [comment]
Assuming this is problem with code that assumes certain reporting on cdata segments; can not reproduce without unit test or code snippet.
