### ISSUE TITLE
Inconsistent reading of formatted xml when validating schema

### ISSUE THREAD

**Issue by elrodro83** [FasterXML/woodstox#29]
When setting a reader to validate schema, the spaces between the tags returned generate a SPACE event, while the same read without validation return a CHARACTERS event.

Adding this test to `TestW3CSchema` shows the issue:

```
  public void testFormattedXml() throws XMLStreamException {
      // Another sample schema, from
      String SCHEMA = "<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>\n"
          + "<xs:element name='item'>\n"
          + " <xs:complexType>\n"
          + "  <xs:sequence>\n"
          + "   <xs:element name='quantity' type='xs:positiveInteger'/>"
          + "   <xs:element name='price' type='xs:decimal'/>"
          + "  </xs:sequence>"
          + " </xs:complexType>"
          + "</xs:element>"
          + "</xs:schema>";
      
      XMLValidationSchema schema = parseW3CSchema(SCHEMA);
      
      // First, valid doc:
      String XML = "<item>\n    <quantity>3</quantity>\n    <price>4.05</price>\n</item>";
      XMLStreamReader2 sr = getReader(XML);
      sr.validateAgainst(schema);
      
      assertEquals(XMLStreamConstants.START_ELEMENT, sr.next());
      assertEquals(XMLStreamConstants.CHARACTERS, sr.next());
      assertEquals("\n    ", sr.getText());
      assertEquals(XMLStreamConstants.START_ELEMENT, sr.next());
    }
```

This test fails as is, but if the line `sr.validateAgainst(schema);` is removed, the test runs fine.

I think the correct behaviour for this case would be to return SPACE.

**Comment by elrodro83** [comment]
This is happening with commit 1d7affd and version 4.4.1.

**Comment by cowtowncoder** [comment]
If I understand you description correctly, behavior is as expected. There is no way to reliably consider a sequence of whitespace characters to be definitely ignorable whitespace (logical event) without schema information. It may just happen to be white space, but could be regular text segment. This determination depends solely on schema declaration, whether there is cdata expected, or not -- it's ignorable white space only in latter case (and if there was some other character data this would be validity violation).

So the code works as intended unless I am missing something.

**Comment by elrodro83** [comment]
Fair enoigh. Seems the issue is un cxf then. Already sent a pr forma that. Thanks for the input!

**Comment by cowtowncoder** [comment]
@elrodro83 No problem: this is a confusing aspect and earlier handling (woodstox 1.x or 2.x) may have differed. Stax specification is sometimes vague or mum about some aspects as well,.

But use of SPACE vs CHARACTERS now is based on my best understanding of the specs, javadocs and such.
