### ISSUE TITLE
5.0.0 Maven jar missing classes

### ISSUE THREAD

**Issue by norrisjeremy** [FasterXML/woodstox#3]
It appears the 5.0.0 Maven published jar is missing all the class files:

jar -tvf woodstox-core-5.0.0.jar 
   907 Mon Feb 23 20:28:58 CST 2015 META-INF/MANIFEST.MF
     0 Mon Feb 23 20:28:58 CST 2015 META-INF/
     0 Mon Feb 23 20:28:58 CST 2015 META-INF/maven/
     0 Mon Feb 23 20:28:58 CST 2015 META-INF/maven/com.fasterxml.woodstox/
     0 Mon Feb 23 20:28:58 CST 2015 META-INF/maven/com.fasterxml.woodstox/woodstox-core/
   144 Mon Feb 23 20:28:58 CST 2015 META-INF/maven/com.fasterxml.woodstox/woodstox-core/pom.properties
  6609 Mon Feb 23 20:28:38 CST 2015 META-INF/maven/com.fasterxml.woodstox/woodstox-core/pom.xml
     0 Mon Feb 23 20:28:58 CST 2015 META-INF/services/
    35 Mon Feb 23 20:28:38 CST 2015 META-INF/services/javax.xml.stream.XMLEventFactory
    34 Mon Feb 23 20:28:38 CST 2015 META-INF/services/javax.xml.stream.XMLInputFactory
    35 Mon Feb 23 20:28:38 CST 2015 META-INF/services/javax.xml.stream.XMLOutputFactory
    34 Mon Feb 23 20:28:38 CST 2015 META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.dtd
    38 Mon Feb 23 20:28:38 CST 2015 META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.relaxng
    34 Mon Feb 23 20:28:38 CST 2015 META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c

**Comment by cowtowncoder** [comment]
Ouch. Thank you for reporting this -- I thought I had validated it all locally, before pushing release. Obviously something went wrong.

**Comment by cowtowncoder** [comment]
Was caused due to difference between Java package name, Maven group id -- default parent pom works if the two are the same. Added proper override.
