### ISSUE TITLE
Java 9-ea+164 jdeps warning

### ISSUE THREAD

**Issue by huxi** [FasterXML/woodstox#34]
`jdeps -jdkinternals` of Java 9-ea+164 produces the following warning for projects using `woodstox-core:5.0.3`:
```
com.ctc.wstx.msv.GenericMsvValidator
-> org.relaxng.datatype.Datatype
JDK internal API (JDK removed internal API)
```

This issue is just meant as an "in case you didn't know".

**Comment by cowtowncoder** [comment]
I think this was resolved by #78 (although not necessarily). But since Java 9 itself has been EOL'd for a while, closing this (may re-file if occurs with Java 11 or 14 [that is, a newer LTS version])
