### ISSUE TITLE
com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '/' (code 47) (expected a name start character)

### ISSUE THREAD

**Issue by dajoropo** [FasterXML/woodstox#36]
Hello,

I'm having an issue unmarshaling an XML file when some special characters as "/" are included inside one attribute.

In the .xsd file, the attribute is defined as normalized String, and as far as I know the character / is allowed:
```
<xs:element name="field" maxOccurs="unbounded">
	<xs:complexType>
		<xs:attribute name="name" type="xs:token" use="required" />
		<xs:attribute name="value" type="xs:normalizedString" use="required" />
	</xs:complexType>
</xs:element>
```

This is one sample value in the field:
`<field name = "test" value = "test/"/>`

And here the call I make:
```
XMLStreamReader xsr = null;
try {
	// Create the XML stream reader
	XMLInputFactory xif = XMLInputFactory.newFactory();
	xsr = xif.createXMLStreamReader(inputStream, "UTF-8");

	// Unmarshall the XML with JAXB, with XML schema validation enabled
	JAXBContext jc = JAXBContext.newInstance(Root.class);
	Unmarshaller unmarshaller = jc.createUnmarshaller();
	unmarshaller.setSchema(this.xmlSchema);
	Root rootIndex = (Root) unmarshaller.unmarshal(xsr);
	[...]
}
```
From what I've found, the issue happens in StreamScanner.fullyResolveEntity. Is this working as expected? is the character "/" not allowed?

**Comment by dajoropo** [comment]
Closed as is not really an issue. I had wrong test data: a not escaped & before the / was provoking the issue and not the / itself. Escaping the & as &amp; fixed the issue.

**Comment by cowtowncoder** [comment]
Ok.
