### ISSUE TITLE
Maybe too strict validation for CDATA value

### ISSUE THREAD

**Issue by libetl** [FasterXML/woodstox#40]
Hello,

my work is to nest "stringified xml with cdata" inside cdata (don't blame me, legacy code).
It is not working as expected because of https://github.com/FasterXML/woodstox/blob/master/src/main/java/com/ctc/wstx/sw/BufferingXmlWriter.java#L1484

actually my cdata escaped text contains this :

```xml
<Name><![CDATA[John Doe]]]]><![CDATA[></Name>
```
That stackoverflow thread learned me that it can work : https://stackoverflow.com/questions/223652/is-there-a-way-to-escape-a-cdata-end-token-in-xml

Please advise, do you think we should fix it ? Or am I wrong ?
Thanks for your help.

**Comment by cowtowncoder** [comment]
Have a look at XML specification (https://www.w3.org/TR/REC-xml/), sections 2.4, 2.7 for details of what is allowed. And if you think there is a bug, please include code that exhibits it.
Above is not enough to know exactly what you are trying to do.

As to possible workaround -- depending on exactly what you are trying to do -- it may be useful to read:

https://medium.com/@cowtowncoder/configuring-woodstox-xml-parser-woodstox-specific-properties-1ce5030a5173

and specifically check out `P_OUTPUT_FIX_CONTENT` and/or `P_OUTPUT_VALIDATE_CONTENT`.
Former can help work around issues of trying to produce invalid text content (by splitting things); latter is what triggers exception, and if you processing pipeline does not validate content, it might accept things like `]]>` outside of `CDATA` segment (despite it being invalid as per XML specification - some parsers do not validate everything spec mandates).

**Comment by libetl** [comment]
Thanks for these details. Closing the issue.
