### ISSUE TITLE
webservices-*2.1.1.jar when used with woodstox-core-asl-4.4.1.jar conflicts due to class com.ctc.wstx.sr.ValidatingStreamReader

### ISSUE THREAD

**Issue by sarsjits** [FasterXML/woodstox#45]
I have found that when webservices-*2.1.1.jar is used with woodstox-core-asl-4.4.1.jar there is a conflict due to com.ctc.wstx.sr.ValidatingStreamReader class. This happens because XMLStreamReaderFactory.create in StreamSOAPCodec returns ValidatingStreamReader which is present in both the jars.

**Comment by cowtowncoder** [comment]
Is this issue filed in wrong place? Shouldn't it belong to whatever project provides `webservices` jar?
Which is not Woodstox.
