### ISSUE TITLE
invisible CHARACTER data

### ISSUE THREAD

**Issue by fommil** [FasterXML/woodstox#52]
I may be misunderstanding the XML spec, but I am unable to see the `wobble` in the following snippet

```xml
<?xml version="1.0" encoding="UTF-8"?>
       <root>
       <foo>wibble</foo>
       <foo>
         <bar>
          fish
         </bar>
           wobble
       </foo>
       <foo>fish</foo>
       </root>
```

with woodstox or aalto.

If I put the `wobble` before any other tags, it is seen. Text is also ignored if it's between two tags, e.g.

```xml
<?xml version="1.0" encoding="UTF-8"?>
       <root>
       <foo>wibble</foo>
       <foo>
         wobble1
         <bar>
          fish
         </bar>
           wobble
         <bar2>
          fish
         </bar2>
       </foo>
       <foo>fish</foo>
       </root>
```

I thought XML was supposed to support "mixed content".

**Comment by fommil** [comment]
I need to get legal clearance before sharing code, so it would have come eventually. But.... I spotted a bug so I'll just close this as PEBKAC...

**Comment by cowtowncoder** [comment]
Ok. Can always re-open/re-file if there are remaining issues.
