### ISSUE TITLE
Exception type does not correspond

### ISSUE THREAD

**Issue by Aifeng1214** [FasterXML/woodstox#55]
https://github.com/FasterXML/woodstox/blob/bae0330b0c2895b4aeb35ac83aa961d7f29bfa66/src/main/java/com/ctc/wstx/stax/WstxInputFactory.java#L643

The function claims that it throws XMLStreamException but here it throws IllegalArgumentException which may cause uncatchable exception.

**Comment by cowtowncoder** [comment]
Since `IllegaArgumentException` is unchecked one, I am not sure this is necessary incompatible with documentation.

Passing `null` also seems like a simple bug, so I am actually not sure what the specific issue here is.
