### ISSUE TITLE
XMLStreamReader reports "no namespace" (aka default namespace) for attributes as "", not `null`

### ISSUE THREAD

**Issue by Claudenw** [FasterXML/woodstox#57]
I believe the XMLStreamReader incorrectly handles default namespaced attributes.  The relevant documentation can be found at.

https://www.w3.org/TR/2006/REC-xml-names11-20060816/#defaulting

>  Default namespace declarations do not apply directly to attribute names; the interpretation of unprefixed attributes is determined by the element on which they appear.

and 

https://www.w3.org/TR/2006/REC-xml-names11-20060816/#uniqAttrs

> ... the second because the default namespace does not apply to attribute names:

In my example code I show that woodstox produces the default namespace (an empty string) when 
```staxReader.getAttributeNamespace( 0 )``` is called while the ```com.sun.xml.internal.stream.XMLInputFactoryImpl``` implementations returns ```null```

I believe the sun implementation is correct.

example code attached:
[ExampleCode.zip](https://github.com/FasterXML/woodstox/files/2145807/ExampleCode.zip)

**Comment by cowtowncoder** [comment]
I think the question is not so much about namespace handling -- which Jackson does obey, and never produces any non-namespace URI even if default namespace is bound to one -- but API compatibility wrt how to report "empty" or "default" namespace (terminology gets bit ambiguous).
That is just to say that I think XML specification is clear, but question pertains to Java Stax API.

And this is the problem since Stax 1.0 was quite loosely specified (partly covered by Javadocs, some areas seemingly undefined). Worse, Sun/Oracle do not give TCKs for OSS projects except ones under organizations that are JSR/JCP members. So we have not and do not have access to Stax TCK.
JDK internal implementation may have compliant behavior, but I just need to find something somewhere that confirms behavior. One possibility would be later Stax API specification (or even original if there is mention).

Having said all that, you may want to enable

    WastInputProperties.P_RETURN_NULL_FOR_DEFAULT_NAMESPACE

(via `setProperty()` on `WstxInputFactory`, I think?)

since that seems to ... actually be for it.

If and when I have time to work on Woodstox again I should see if we can change the default.
By javadoc looks like it should already have been changed...

**Comment by Claudenw** [comment]
My problem is that I am utilizing the Apache Jena library to read/write RDF.  When working in the TriX format that library uses the registered XMLInputFactory to retrieve and use an XMLStreamReader so I have no access to the factory.  

In addition, the only reason t hat Woodstox is being uses is because jackson-dataformat-xml is included in one of the other packages I am using.

There is a discussion of this in a Jena issue (https://issues.apache.org/jira/browse/JENA-1567)

I am willing to take a look and see if I can provide a patch now that I know what is missing.

**Comment by cowtowncoder** [comment]
To further complicate things, JDK Stax javadocs:

https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLStreamReader.html#getAttributeNamespace-int-

only state:

    Returns:  the namespace URI (can be null)

which does not quite answer the question. Yet worse is:

https://docs.oracle.com/javase/8/docs/api/javax/xml/XMLConstants.html#NULL_NS_URI

which seems to suggest that the right answer is actually "", NOT `null`.

Given all of this, I think that any Java XML library that uses Stax API should consider both `null` and "" to mean "no namespace" for attributes, and not doing that is relying on undocumented behavior.

**Comment by Claudenw** [comment]
I stand by my interpretation of the XML standards (https://www.w3.org/TR/2006/REC-xml-names11-20060816).  If the namespace does not apply it should be NULL not "" as "" is a designated namespace (the default one).  The document clearly states that the default namespace does NOT apply to attributes.

I believe that https://www.w3.org/TR/2006/REC-xml-names11-20060816 is the canonical definition and that www.w3.org is the system of record for XML definition.

**Comment by cowtowncoder** [comment]
I do not understand why you keep reiterating XML specification, which has little relevance to Java side. There is literally no distinction between empty String or null in XML spec (no such concept exists); so lacking a namespace (URI) and having whatever default might be are all but equivalent.

This leaves the question of how to convey this via Java API. Some people prefer `null`. Others hate nulls in all form and/or prefer empty String.

And this behavior needs to be specified. As far as I can see, JDK is on non-null camp.

If you can state JAVA side specification that unambiguously shows specific behavior to be "return null", I can consider the change (subject to backwards compatibility concerns). But until then I see no benefit from change that seems as likely to break Stax API compatibility as not.

**Comment by Claudenw** [comment]
How about we look at this from the XML specification section on uniqueness of attributes discussion of duplicate attributes not being allowed.

```

For example, each of the bad empty-element tags is illegal in the following:

<!-- http://www.w3.org is bound to n1 and n2 -->
<x xmlns:n1="http://www.w3.org" 
   xmlns:n2="http://www.w3.org" >
  <bad a="1"     a="2" />
  <bad n1:a="1"  n2:a="2" />
</x>

However, each of the following is legal, the second because the default namespace does not apply to attribute names:

<!-- http://www.w3.org is bound to n1 and is the default -->
<x xmlns:n1="http://www.w3.org" 
   xmlns="http://www.w3.org" >
  <good a="1"     b="2" />
  <good a="1"     n1:a="2" />
</x>

```

The woodstox parser (as coded) will not parse the second one properly. as the `a="1" values will return the namespace of "" which will resolve to `http://www.w3.org`, the same name as `n1:a="2"`.

It seems to me that is not correct, but that is what woodstox will do.

**Comment by Claudenw** [comment]
You reference the oracle documentation but the sun XML parser (distributed by Oracle) returns null not "" in the cases in question as is shown in the example code I originally included.

**Comment by Claudenw** [comment]
From the Java Community Process site:
XML API for JavaTM ME (http://jcp.org/aboutJava/communityprocess/final/jsr280/index.html)
Specification download: https://download.oracle.com/otndocs/jcp/xml_me-1.0-fr-oth-JSpec/

api/org/w3c/dom/Node.html#getNamespaceURI()

```
 getNamespaceURI

public String getNamespaceURI()

    The namespace URI of this node, or null if it is unspecified.
    This is not a computed value that is the result of a namespace lookup based on an examination of the namespace declarations in scope. It is merely the namespace URI given at creation time.
    For nodes of any type other than ELEMENT_NODE and ATTRIBUTE_NODE and nodes created with a DOM Level 1 method, such as Document.createElement, this is always null.

    Note: Per the Namespaces in XML Specification [XML Namespaces] an attribute does not inherit its namespace from the element it is attached to. If an attribute is not explicitly given a namespace, it simply has no namespace.

    Returns:
        The namespace URI of this node, or null
    Since:
        DOM Level 2

```

**Comment by cowtowncoder** [comment]
On "" resolving, no: I do not see this as incorrect. Examples from XML specification make sense from processing standpoint but are not in contradiction to Woodstox behavior.
Namespace URI "" can never resolve to anything other than missing/empty namespace -- only prefix "" (or missing) resolves to it. So I do not quite see the problem. While it is true that naive processor could try to resolve "" reported as prefix to namespace URI, that seems pointless: namespace URI is already accessible as separate piece of information, and will give the correct answer. Indirect resolution will not, but it's worth remembering that namespace prefixes are ephemeral things in XML Infoset, shortcuts only used in serialization and all processing should be based on namespace URI.
(... and we are not even discussing proper return value for missing prefix here)

As to `getNamespaceURI()`: that is part of DOM specification, not Stax, so it is not directly relevant either -- it may help figure out common practices in absence of other information, but it is not method implemented by Stax API even if there is a method of same name for different class.

Finally, as to Oracle's Stax implementation: that is a weak suggestion, and I do not take it as canonical behavior. This partly based on remembering all bug reports (and many bug fixes accepted) I contributed years ago. Reference Implementation has its warts.

I would accept reference within Stax API (1.0, 1.1 or subsequent if any; or, relevant sections in JAXP spec updates) as definitions.
Or if anyone has access to Stax TCK that would also qualify. Or comment by current spec lead (lead of most current version).

But aside from that there is literally only downside for me if I were to change reporting from one value to another. Someone's code somewhere is almost guaranteed to count on existing behavior, leading to other bug reports for change. And this is where pointing to actual documentation on specified Stax API behavior helps.
