### ISSUE TITLE
Docs do not explain how to set properties

### ISSUE THREAD

**Issue by ST-DDT** [FasterXML/woodstox#59]
The docs do explain which properties should be set and roughly where:

> **Finding Property name definitions**
> 
> Woodstox-specific property names are defined in 2 classes:
> 
> *   WstxInputProperties (to use via XMLInputFactory)
> *   WstxOutputProperties (to use via XMLOutputFactory)
> 
> As with all properties, configuration is done using methods XMLInputFactory.setProperty() and XMLOutputFactory.setProperty().

from https://medium.com/@cowtowncoder/configuring-woodstox-xml-parser-woodstox-specific-properties-1ce5030a5173

but it does not explain how do actually do this (in my case on Jackson's XMLMapper).

After searching through the interfaces for quite some time I found a solution I assume to work, it would be nice if this could be added to the documentation for easier access:

````java
XmlMapper xmlMapper = new XmlMapper();
xmlMapper.getFactory().getXMLInputFactory().setProperty(WstxInputProperties.P_MAX_ATTRIBUTE_SIZE, Integer.MAX_VALUE);
````

Setting the value via system properties doesn't seem to work (which was my first assumption).

**Comment by cowtowncoder** [comment]
I added bit of verbiage to README here, and will check out Jackson XML module as well.
Let me know what you think; PRs welcome too!

**Comment by ST-DDT** [comment]
While it is nice that you included the links to the configuration options directly in the readme it still does not explain how you can get the xmlinput and outputfactories. Please add a sentence like 

> You can access them via `xmlMapper.getFactory().getXMLInputFactory()` and `xmlMapper.getFactory().getXMLOutputFactory().`.

**Comment by cowtowncoder** [comment]
@ST-DDT I don't think that is actually the best way to do it: ideally one provides `XmlFactory` that has underlying Stax input/output factories. One should not usually need factories directly, aside from passing properly configured instances. Factories are considered private configuration, although they obviously can be accessed if absolutely necessary.

**Comment by ST-DDT** [comment]
Oh. I haven't noticed that. Then maybe add a few lines that explain how to configure those factories and how to set them to/use them with the XmlMapper?

**Comment by cowtowncoder** [comment]
I did change README of xml module:

https://github.com/FasterXML/jackson-dataformat-xml/

.... oh. But I change 2.9 branch and hadn't merged to `master`. Changed now.
So that's why confusion. Thank you for pointing this out.
