### ISSUE TITLE
xmls of different size results in different namespaces - SOAP - apache-cxf

### ISSUE THREAD

**Issue by amarkin** [FasterXML/woodstox#63]
We have a SOAP API client generated from apache cxf and when invoking the SOAP service using the client stubs we are running into an issue which we believe is related to the xml size.

When the xml size(length) increases beyond a certain value the name space is identified as **http://www.w3.org/2003/05/soap-envelope** instead of  **http://schemas.xmlsoap.org/soap/envelope/**

The namespace is identified as different for different length files. The soap api client stubs are generated based of SOAP 1.1 as per the WSDL, when the program identifies the SOAP envelope xml as 1.1 for smaller length files it works fine. When the SOAP envelope xml is identified as 1.2 system throws a validation saying - **A SOAP 1.2 message is not valid when sent to a SOAP 1.1 only endpoint**

**ValidatingStreamReader** --> **mConfig** -->**mCurrRecycler** --> **mSmallCBuffer** (or mElementStack --> mCurrentElement) gets a value assigned which includes the namespace. when the getEventType() or nextTag() APIs are executed on the XMLStreamReader which point to the ValidatingStreamReader object.

```
XMLStreamReader xmlReader = message.getContent(XMLStreamReader.class);

if (xmlReader.getEventType() == XMLStreamConstants.START_ELEMENT
                || xmlReader.nextTag() == XMLStreamConstants.START_ELEMENT) {

}
```

Please note there is no difference in the xml content, except the larger xml has few more <Path> attributes as shown in the image below. Other than that the xml content is exactly same for both small and large sizes.

![image](https://user-images.githubusercontent.com/8661117/44829105-e302ed80-abcf-11e8-835b-350542d63f4a.png)

If you could help us understand what is going on here and provide a solution that would be great 
help.

Thanks
Amar.

**Comment by amarkin** [comment]
@cowtowncoder 

Can you please help us take a look at this issue.

Thanks
Amar.

**Comment by cowtowncoder** [comment]
@amarkin What would help a lot would be unit test, or similar reproduction. I do not have a good guess on what might be going on, and although knowing some difference (diff size) is useful information, it is not much to go on.

**Comment by cowtowncoder** [comment]
Can not reproduce as described; may be reopened with reproduction.
