### ISSUE TITLE
Support for Java 11

### ISSUE THREAD

**Issue by nirupamarachuri** [FasterXML/woodstox#64]
@cowtowncoder 
Is there any release planned for woodstox-core that supports Java 11? If yes, when is it scheduled to release?

**Comment by cowtowncoder** [comment]
@nirupamarachuri No plans. If anyone has time to check what problems there are, if any, that would be helpful. Some investigation was done for Java 9, with no problems that I recall, so Java 11 might "just work".

**Comment by nirupamarachuri** [comment]
@cowtowncoder 

For woodstox-core v5.0.3 the jdeps scan returns the following error:

woodstox-core-5.0.3.jar -> JDK removed internal API com.ctc.wstx.msv.GenericMsvValidator -> org.relaxng.datatype.Datatype JDK internal API (JDK removed internal API)

What version is compatible with Java 11?
