### ISSUE TITLE
com.ctc.wstx.exc.WstxParsingException: Undeclared general entity "Aacute"

### ISSUE THREAD

**Issue by mrlimbic** [FasterXML/woodstox#66]
I need to deal with some XML that has strange attributes where chinese characters are encoded as entities. Any help would be appreciated.

`<string name="Name" value="&Aacute;&yacute;&frac34;&micro; &ordm;&pound;&Iacute;&otilde;&Ocirc;&curren;&cedil;&aelig;&AElig;&not;-01.wav"/>`

The name should be decoded eventually as 慢镜 海王预告片-01.wav

It is possibly GB10830 rendered as Latin-1 entities.

Is there an entity resolver implementation for woodstox that knows the full set of W3C entities below?

https://www.w3.org/TR/xml-entity-names/bycodes.html

**Comment by mrlimbic** [comment]
How would I configure Woodstox to use the following DTD which contains the W3C entity definitions?

https://www.w3.org/2003/entities/2007/w3centities-f.ent

**Comment by cowtowncoder** [comment]
I'd have to go dig up details when I have more time, but the idea is that you can create DTD schema factory, read external DTD, and make XMLStreamReader use that schema. There should be unit test(s) that do that -- mechanism is exposed same way as W3C Schema, RelaxNG schemas, for validation, but I think should also allow declaration of entities being imported.
