### ISSUE TITLE
Woodstox is not parsing nested tags in executable jar.

### ISSUE THREAD

**Issue by surekha1317** [FasterXML/woodstox#69]
I am using woodstox to parse xml, xlf, html files. This is working very well when run it as a java program but when I convert it to jar then behaviour is strange. It is not parsing nested tags.
Ex:  "\<source\> \<span\> span text \</span\> \<span\> another sapn text \</span\> source value \</source\>"

I this case If I am trying to extract <source> value I should ideally get  "span text another sapn text source value"  but I am getting  "<span> span text </span> <span> another sapn text </span> source value " in jar execution. I did not really understand why it is making difference.

Here are the dependencies I am using for woodstox

	<dependency>
			<groupId>org.codehaus.woodstox</groupId>
			<artifactId>stax2-api</artifactId>
			<version>4.1</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.woodstox</groupId>
			<artifactId>woodstox-core-asl</artifactId>
			<version>4.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.codehaus.woodstox</groupId>
			<artifactId>woodstox-core-lgpl</artifactId>
			<version>4.4.1</version>
		</dependency>

**Comment by cowtowncoder** [comment]
You have not included much pertinent information: this is unfortunately not enough to help you.

But if you can include actual code to show what you are doing, and what you see, maybe I can help figure out what needs to be changed.

**Comment by surekha1317** [comment]
Thanks for your reply. This is my code to parse xlf file:

               try {
			XMLStreamReader2 xmlStreamReader = (XMLStreamReader2) xmlInputFactory
					.createXMLStreamReader(fileName.toString(), new FileInputStream(fileName));
			
			while (xmlStreamReader.hasNext()) {
				int eventType = xmlStreamReader.next();
				switch (eventType) {
				case XMLEvent.START_ELEMENT:
					String startTag = xmlStreamReader.getLocalName();
					if ("group".equalsIgnoreCase(startTag)) {
						resname = getAttribute(xmlStreamReader, "resname");
					} else if ("source".equalsIgnoreCase(startTag)) {
						source = true;
					}
					break;
				case XMLEvent.CHARACTERS:
					if (source) {
						sourceVal += xmlStreamReader.getText();
					}
					break;
				case XMLEvent.END_ELEMENT:
					String endTag = xmlStreamReader.getLocalName();
					if ("group".equalsIgnoreCase(endTag)) {
						resname = "";
					} else if ("source".equalsIgnoreCase(endTag)) {
						source = false;
						if (!sourceVal.equals("") && sourceVal != null) {
							// logic to get examine source val.
						}
						sourceVal = "";
					}
				}
			}  
		} catch (Exception e) {
			System.out.println(e);
		}

**Comment by surekha1317** [comment]
Please check above code and let me know if there are any issues in my code.

**Comment by cowtowncoder** [comment]
Ok it's bit difficult to make sure I understand original statement with code, but I do not see immediate problems with it, except for one possible thing.

But one thing I'd suggest is to look for ALL events -- you don't have default case, and one possbile event type is `XMLStreamConstants.SPACE`, which may be reported when DTD or Schema validation indicate that content is ignorable white space. That should not really be the case for textual markup, unless Schema is truly saying whitespace within may be discarded at will, but based on description that sounds likely. Either way if you really do think it is thing to included, handle `SPACE` same as `CHARACTERS`.

**Comment by cowtowncoder** [comment]
Can not reproduce the issue at this point. May be reopened with reproduction.
