### ISSUE TITLE
Invalid 5.0.0 on mvnrepository

### ISSUE THREAD

**Issue by lejeunen** [FasterXML/woodstox#7]
It seems there is an issue with version 5.0.0 on mvnrepository, it's only 6Kb. See http://mvnrepository.com/artifact/com.fasterxml.woodstox/woodstox-core/5.0.0 

Version 5.0.1 is fine though, so you could just update the README to indicate 5.0.1 is the version to use.

**Comment by cowtowncoder** [comment]
Yes, good point on README. And apologies for messing up 5.0.0 -- unfortunately I don't know of a way to remove that version from Maven central.
