### ISSUE TITLE
Error reading xml with newlines in XML Declaration

### ISSUE THREAD

**Issue by Teg79** [FasterXML/woodstox#72]
When the XML Declaration contains newlines the parser throws and exception

**XML**
```
<?xml
version="1.0"
encoding="UTF-8"?>
<root>
</root>
```

**Error**
`WstxParsingException: Illegal processing instruction target ("xml")`

**Comment by cowtowncoder** [comment]
It's not newlines in general, but specifically any whitespace BEFORE the first `<`. XML specification (https://www.w3.org/TR/xml/) is clear on that:

1. XML declaration, if any, must be the very first thing in document (no, not even whitespace allowed before)
2. No user-defined processing instruction may use target of `xml` (it is reserved target name, similar to `xmlns`)

So, in your case what might appear as xml declaration is no one, it's just an invalid processing instruction. You can verify this by looking at production with first rule [1] to prolog to xml declaration.

Other newlines are fine within (as per linefeed validity rules). To fix the problem you may need to trim the input String (if it comes as a String), or have a `Reader` that skips leading white space.

This is of course cumbersome from user perspective, knowing how many weird systems exist that produce half-ass XML (or close). But XML parsers are unfortunately required to follow specification as is.

I guess it would be possible for a new parsing feature to be added to allow skipping such white space, as well, if anyone wanted to give that a go -- I am not against off-by-default features that allow skipping some well-formedness constraints; some already exist. But not for this one.

**Comment by Teg79** [comment]
The problem is the system generating he broken xml, not the parser, you're right.
I'll put an adapter before the parsing
