### ISSUE TITLE
Infinite loop in BijectiveNsMap#addGeneratedMapping when ctxt.getNamespaceURI(prefix) returns an empty String

### ISSUE THREAD

**Issue by ioanmarcu** [FasterXML/woodstox#74]
According to the specification of NamespaceContext#getNamespaceURI, XMLConstants.NULL_NS_URI("") is an accepted return value for this method.

This case is however not treated in `BijectiveNsMap#addGeneratedMapping`, line 290: 

 `if (ctxt != null && ctxt.getNamespaceURI(prefix) != null) {
       continue;
  }`
			
When NamespaceContext#getNamespaceURI returns an empty String, it will result in an infinite loop.
			
A small test that verifies this: [TestEmptyNamespace.zip](https://github.com/FasterXML/woodstox/files/3171989/TestEmptyNamespace.zip)

Marginally relevant issue: #8

**Comment by cowtowncoder** [comment]
Thank you for reporting this, will fix.

**Comment by cowtowncoder** [comment]
Released `5.2.1` as well since although this is the only fix, the issue itself would be quite nasty to encounter.
