### ISSUE TITLE
XMLStreamWriter.setPrefix

### ISSUE THREAD

**Issue by buko** [FasterXML/woodstox#79]
According to the [Javadoc contract for XMLStreamWriter#setPrefix](https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLStreamWriter.html#setPrefix-java.lang.String-java.lang.String-):

`Sets the prefix the uri is bound to. This prefix is bound in the scope of the current START_ELEMENT / END_ELEMENT pair. If this method is called before a START_ELEMENT has been written the prefix is bound in the root scope.`

This doesn't seem to work with the latest Woodstox (5.2.1):

Code like:

```java
final XMLStreamWriter writer = xmlOutputFactory.createXMLStreamWriter(System.out, "UTF-8");
writer.setPrefix("log", AXmlNamespace.NAMESPACE_URI);
writer.setPrefix("module"BXmlNamespace.NAMESPACE_URI);
writer.setPrefix("xlink", XLinkNamespace.NAMESPACE_URI);
writer.writeStartDocument();
writer.writeStartElement(AXmlNamespace.NAMESPACE_URI, "entries");
```

Does not cause the appropriate `xmlns` attributes to actually appear on the root node. Instead only the 'A' namespace prefix is declared on the root node.

This leads to further pathological behavior, I think. Because the namespaces aren't in scope on the root node woodstox will declare these prefixes on virtually every xml element in the stream.

I think Woodstox should follow the javadoc and do what the RI does and bind prefixes called before a startElement has been written to the root node.

Workaround:

It is possible to explicitly bind prefixes on the root node by calling writer.writeNamespace after the root node start element has been written. If you do that the output looks much nicer!

**Comment by cowtowncoder** [comment]
You may be misunderstanding functioning of Stax writers and `setPrefix()`; it varies based on whether "namespace repairing" is enabled or not (and it is not by default).

In both modes `setPrefix()` only establishes mapping to use from namespace URI to prefix and does not directly cause namespace declaration to be written: declaration will be either:

1. Written when explicit call to `writeNamespace` is made (in any mode)
2. When namespace binding is required by `writeStartElement()` or `writeAttribute()` call AND namespace-repairing mode is enabled.

`setPrefix()` is not very useful in that sense as it doesn't do much; and even in ns-repairing mode you can simply just pass NS URI and prefix on write call to establish preferred binding.

Above is my understanding of the Stax specification. I can see how Javadoc comment could be construed to perhaps imply something more.

**Comment by buko** [comment]
Alright, that's a bit surprising. I have Namespace-repairing mode enable and was actually seeing the declarations being written by the RI but yeah, what you say also makes sense. Perhaps it's really a Javadoc bug.

**Comment by cowtowncoder** [comment]
@buko Stax specification has always been quite vague, underspecified :-/

So I can definitely see how existing Javadoc could lead to thinking the way you did. My understanding is based on working with the original specification years ago, which was even more sparse.
