### ISSUE TITLE
TestEntityResolver#testWithDummyExtSubset fails on windows

### ISSUE THREAD

**Issue by Dragas** [FasterXML/woodstox#84]
It seems that the test expects a unix-like error message which says "No such file or directory" while the following error is thrown on windows instead:

```
[ERROR] Failures: 
[ERROR]   TestEntityResolver.testWithDummyExtSubset:41->BaseStax2Test.verifyException:570 Expected an exception with sub-string "No such file or directory": got one with message "(was java.io.FileNotFoundEx
ception) C:\Users\M9X\IdeaProjects\woodstox\no-such-thing.dtd (The system cannot find the file specified)
 at [row,col {unknown-source}]: [1,63]"
[INFO]
[ERROR] Tests run: 841, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by cowtowncoder** [comment]
Thank you for reporting this platform-dependency.

**Comment by cowtowncoder** [comment]
I can't test this easily (I don't have windows machine), but I think change I made should make it pass on windows and hopefully other platforms. Did not realize that underlying exception is platform-specific.
