### ISSUE TITLE
OSGi dependency on relaxng should be `optional`

### ISSUE THREAD

**Issue by coheigea** [FasterXML/woodstox#85]
There is a dependency in OSGi on relaxng, which should be optional.

**Comment by coheigea** [comment]
PR: https://github.com/FasterXML/woodstox/pull/86

**Comment by cowtowncoder** [comment]
Will try to release 6.0.2 soon, to resolve possible issue with OSGi usage.

**Comment by cowtowncoder** [comment]
Just released 6.0.2, should get to Maven Central in an hour or so.

**Comment by coheigea** [comment]
Thanks for the fast turn-around!
